/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rmi.client;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        Question_panel = new javax.swing.JPanel();
        q1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nxt1 = new javax.swing.JButton();
        q1_a1 = new javax.swing.JRadioButton();
        q1_a2 = new javax.swing.JRadioButton();
        q1_a3 = new javax.swing.JRadioButton();
        q2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bck2 = new javax.swing.JButton();
        q2_a1 = new javax.swing.JRadioButton();
        q2_a2 = new javax.swing.JRadioButton();
        nxt2 = new javax.swing.JButton();
        q3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        q3_a1 = new javax.swing.JRadioButton();
        q3_a2 = new javax.swing.JRadioButton();
        q3_a3 = new javax.swing.JRadioButton();
        q3_a4 = new javax.swing.JRadioButton();
        bck3 = new javax.swing.JButton();
        nxt3 = new javax.swing.JButton();
        q4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        q4_a1 = new javax.swing.JRadioButton();
        q4_a2 = new javax.swing.JRadioButton();
        q4_a3 = new javax.swing.JRadioButton();
        q4_a4 = new javax.swing.JRadioButton();
        bck4 = new javax.swing.JButton();
        nxt4 = new javax.swing.JButton();
        q5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        q5_a1 = new javax.swing.JRadioButton();
        q5_a2 = new javax.swing.JRadioButton();
        q5_a3 = new javax.swing.JRadioButton();
        bck5 = new javax.swing.JButton();
        nxt5 = new javax.swing.JButton();
        q6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        q6_a1 = new javax.swing.JRadioButton();
        q6_a2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        bck6 = new javax.swing.JButton();
        nxt6 = new javax.swing.JButton();
        q7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        q7_a1 = new javax.swing.JRadioButton();
        q7_a2 = new javax.swing.JRadioButton();
        bck7 = new javax.swing.JButton();
        nxt7 = new javax.swing.JButton();
        q8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        q8_a1 = new javax.swing.JRadioButton();
        q8_a2 = new javax.swing.JRadioButton();
        bck8 = new javax.swing.JButton();
        nxt8 = new javax.swing.JButton();
        q9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        q9_a1 = new javax.swing.JRadioButton();
        q9_a2 = new javax.swing.JRadioButton();
        bck9 = new javax.swing.JButton();
        nxt9 = new javax.swing.JButton();
        q10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        q10_a1 = new javax.swing.JRadioButton();
        q10_a2 = new javax.swing.JRadioButton();
        q10_a3 = new javax.swing.JRadioButton();
        bck10 = new javax.swing.JButton();
        nxt10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Background.setBackground(new java.awt.Color(0, 51, 51));

        Question_panel.setBackground(new java.awt.Color(102, 255, 255));
        Question_panel.setLayout(new java.awt.CardLayout());

        q1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("How did you know about ICY DESIRE?");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        nxt1.setBackground(new java.awt.Color(0, 51, 51));
        nxt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt1.setForeground(new java.awt.Color(255, 255, 255));
        nxt1.setText("Next");
        nxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nxt1MouseClicked(evt);
            }
        });
        nxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt1ActionPerformed(evt);
            }
        });

        q1_a1.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup1.add(q1_a1);
        q1_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q1_a1.setText("Word by mouth");

        q1_a2.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup1.add(q1_a2);
        q1_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q1_a2.setText("Social Media");

        q1_a3.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup1.add(q1_a3);
        q1_a3.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q1_a3.setText("Advertisement");

        javax.swing.GroupLayout q1Layout = new javax.swing.GroupLayout(q1);
        q1.setLayout(q1Layout);
        q1Layout.setHorizontalGroup(
            q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q1Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addGroup(q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1_a2)
                    .addComponent(q1_a1)
                    .addComponent(q1_a3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(q1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        q1Layout.setVerticalGroup(
            q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(q1_a1)
                .addGap(40, 40, 40)
                .addComponent(q1_a2)
                .addGap(48, 48, 48)
                .addComponent(q1_a3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(nxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Question_panel.add(q1, "card2");

        q2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Is this your first order?");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        bck2.setBackground(new java.awt.Color(0, 51, 51));
        bck2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck2.setForeground(new java.awt.Color(255, 255, 255));
        bck2.setText("Back");
        bck2.setMaximumSize(new java.awt.Dimension(81, 37));
        bck2.setMinimumSize(new java.awt.Dimension(81, 37));
        bck2.setPreferredSize(new java.awt.Dimension(81, 37));
        bck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck2ActionPerformed(evt);
            }
        });

        q2_a1.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup2.add(q2_a1);
        q2_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q2_a1.setText("Yes");

        q2_a2.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup2.add(q2_a2);
        q2_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q2_a2.setText("No");

        nxt2.setBackground(new java.awt.Color(0, 51, 51));
        nxt2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt2.setForeground(new java.awt.Color(255, 255, 255));
        nxt2.setText("Next");
        nxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q2Layout = new javax.swing.GroupLayout(q2);
        q2.setLayout(q2Layout);
        q2Layout.setHorizontalGroup(
            q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q2Layout.createSequentialGroup()
                .addGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q2Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2_a1)
                            .addComponent(q2_a2)))
                    .addGroup(q2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(q2Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(bck2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 774, Short.MAX_VALUE)
                        .addComponent(nxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        q2Layout.setVerticalGroup(
            q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(q2_a1)
                        .addGap(39, 39, 39)
                        .addComponent(q2_a2)
                        .addGap(43, 294, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bck2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        Question_panel.add(q2, "card3");

        q3.setBackground(new java.awt.Color(153, 255, 255));
        q3.setPreferredSize(new java.awt.Dimension(1038, 670));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("How did you feel about this Ambience?");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        q3_a1.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup3.add(q3_a1);
        q3_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q3_a1.setText("Excellent");

        q3_a2.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup3.add(q3_a2);
        q3_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q3_a2.setText("Nice");

        q3_a3.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup3.add(q3_a3);
        q3_a3.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q3_a3.setText("Average");

        q3_a4.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup3.add(q3_a4);
        q3_a4.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q3_a4.setText("Poor");

        bck3.setBackground(new java.awt.Color(0, 51, 51));
        bck3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck3.setForeground(new java.awt.Color(255, 255, 255));
        bck3.setText("Back");
        bck3.setMaximumSize(new java.awt.Dimension(81, 37));
        bck3.setMinimumSize(new java.awt.Dimension(81, 37));
        bck3.setPreferredSize(new java.awt.Dimension(81, 37));
        bck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck3ActionPerformed(evt);
            }
        });

        nxt3.setBackground(new java.awt.Color(0, 51, 51));
        nxt3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt3.setForeground(new java.awt.Color(255, 255, 255));
        nxt3.setText("Next");
        nxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q3Layout = new javax.swing.GroupLayout(q3);
        q3.setLayout(q3Layout);
        q3Layout.setHorizontalGroup(
            q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q3Layout.createSequentialGroup()
                .addGroup(q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q3Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addGroup(q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q3_a2)
                            .addComponent(q3_a1)
                            .addComponent(q3_a3)
                            .addComponent(q3_a4)))
                    .addGroup(q3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, q3Layout.createSequentialGroup()
                                .addComponent(bck3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, q3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        q3Layout.setVerticalGroup(
            q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(q3_a1)
                        .addGap(27, 27, 27)
                        .addComponent(q3_a2)
                        .addGap(18, 18, 18)
                        .addComponent(q3_a3)
                        .addGap(18, 18, 18)
                        .addComponent(q3_a4)
                        .addGap(30, 152, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bck3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        Question_panel.add(q3, "card3");

        q4.setBackground(new java.awt.Color(153, 255, 255));
        q4.setPreferredSize(new java.awt.Dimension(1038, 670));

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("What is your choice of flavor?");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        q4_a1.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup4.add(q4_a1);
        q4_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q4_a1.setText("Chocolate");

        q4_a2.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup4.add(q4_a2);
        q4_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q4_a2.setText("Vanilla ");

        q4_a3.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup4.add(q4_a3);
        q4_a3.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q4_a3.setText("Strawberry");

        q4_a4.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup4.add(q4_a4);
        q4_a4.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q4_a4.setText("Mixed");

        bck4.setBackground(new java.awt.Color(0, 51, 51));
        bck4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck4.setForeground(new java.awt.Color(255, 255, 255));
        bck4.setText("Back");
        bck4.setMaximumSize(new java.awt.Dimension(81, 37));
        bck4.setMinimumSize(new java.awt.Dimension(81, 37));
        bck4.setPreferredSize(new java.awt.Dimension(81, 37));
        bck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck4ActionPerformed(evt);
            }
        });

        nxt4.setBackground(new java.awt.Color(0, 51, 51));
        nxt4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt4.setForeground(new java.awt.Color(255, 255, 255));
        nxt4.setText("Next");
        nxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q4Layout = new javax.swing.GroupLayout(q4);
        q4.setLayout(q4Layout);
        q4Layout.setHorizontalGroup(
            q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q4Layout.createSequentialGroup()
                .addGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bck4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(q4Layout.createSequentialGroup()
                        .addGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(q4Layout.createSequentialGroup()
                                .addGap(455, 455, 455)
                                .addGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(q4_a1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q4_a2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q4_a3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q4_a4, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(q4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q4Layout.setVerticalGroup(
            q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(q4_a1)
                .addGap(18, 18, 18)
                .addComponent(q4_a2)
                .addGap(18, 18, 18)
                .addComponent(q4_a3)
                .addGap(18, 18, 18)
                .addComponent(q4_a4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nxt4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(bck4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Question_panel.add(q4, "card3");

        q5.setBackground(new java.awt.Color(153, 255, 255));
        q5.setPreferredSize(new java.awt.Dimension(1038, 670));

        jLabel6.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Number of scoops you want?");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        q5_a1.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup5.add(q5_a1);
        q5_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q5_a1.setText("One - Rs.100");

        q5_a2.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup5.add(q5_a2);
        q5_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q5_a2.setText("Two – Rs.150");

        q5_a3.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup5.add(q5_a3);
        q5_a3.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q5_a3.setText("Three – Rs.200");

        bck5.setBackground(new java.awt.Color(0, 51, 51));
        bck5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck5.setForeground(new java.awt.Color(255, 255, 255));
        bck5.setText("Back");
        bck5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck5ActionPerformed(evt);
            }
        });

        nxt5.setBackground(new java.awt.Color(0, 51, 51));
        nxt5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt5.setForeground(new java.awt.Color(255, 255, 255));
        nxt5.setText("Next");
        nxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q5Layout = new javax.swing.GroupLayout(q5);
        q5.setLayout(q5Layout);
        q5Layout.setHorizontalGroup(
            q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q5Layout.createSequentialGroup()
                .addGroup(q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(q5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, q5Layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addGroup(q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q5_a2)
                            .addComponent(q5_a1)
                            .addComponent(q5_a3))
                        .addGap(0, 294, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, q5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bck5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        q5Layout.setVerticalGroup(
            q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q5Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(q5_a1)
                        .addGap(18, 18, 18)
                        .addComponent(q5_a2)
                        .addGap(18, 18, 18)
                        .addComponent(q5_a3)
                        .addGap(22, 235, Short.MAX_VALUE))
                    .addGroup(q5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bck5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nxt5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        Question_panel.add(q5, "card3");

        q6.setBackground(new java.awt.Color(153, 255, 255));
        q6.setPreferredSize(new java.awt.Dimension(1038, 670));

        jLabel7.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("What is your choice on toppings?");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        q6_a1.setBackground(new java.awt.Color(153, 255, 255));
        q6_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q6_a1.setText("Choco chips");

        q6_a2.setBackground(new java.awt.Color(153, 255, 255));
        q6_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q6_a2.setText("Nuts");

        jRadioButton3.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jRadioButton3.setText("Dried fruits");

        jRadioButton4.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jRadioButton4.setText("Whipped cream ");

        jRadioButton5.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton5.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jRadioButton5.setText("Caramel");

        bck6.setBackground(new java.awt.Color(0, 51, 51));
        bck6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck6.setForeground(new java.awt.Color(255, 255, 255));
        bck6.setText("Back");
        bck6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck6ActionPerformed(evt);
            }
        });

        nxt6.setBackground(new java.awt.Color(0, 51, 51));
        nxt6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt6.setForeground(new java.awt.Color(255, 255, 255));
        nxt6.setText("Next");
        nxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q6Layout = new javax.swing.GroupLayout(q6);
        q6.setLayout(q6Layout);
        q6Layout.setHorizontalGroup(
            q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q6Layout.createSequentialGroup()
                .addGroup(q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(q6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, q6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bck6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, q6Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addGroup(q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q6_a2)
                            .addComponent(q6_a1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q6Layout.setVerticalGroup(
            q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(q6_a1)
                .addGap(18, 18, 18)
                .addComponent(q6_a2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addGap(18, 18, 18)
                .addGroup(q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nxt6, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(bck6, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addContainerGap())
        );

        Question_panel.add(q6, "card3");

        q7.setBackground(new java.awt.Color(153, 255, 255));
        q7.setMaximumSize(new java.awt.Dimension(1038, 670));
        q7.setPreferredSize(new java.awt.Dimension(1038, 670));

        jLabel8.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("What is your preference on sugar? ");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        q7_a1.setBackground(new java.awt.Color(153, 255, 255));
        q7_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q7_a1.setText("With sugar");

        q7_a2.setBackground(new java.awt.Color(153, 255, 255));
        q7_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q7_a2.setText("With sweetener");

        bck7.setBackground(new java.awt.Color(0, 51, 51));
        bck7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck7.setForeground(new java.awt.Color(255, 255, 255));
        bck7.setText("Back");
        bck7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck7ActionPerformed(evt);
            }
        });

        nxt7.setBackground(new java.awt.Color(0, 51, 51));
        nxt7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt7.setForeground(new java.awt.Color(255, 255, 255));
        nxt7.setText("Next");
        nxt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q7Layout = new javax.swing.GroupLayout(q7);
        q7.setLayout(q7Layout);
        q7Layout.setHorizontalGroup(
            q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q7Layout.createSequentialGroup()
                .addGroup(q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q7Layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addGroup(q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q7_a2)
                            .addComponent(q7_a1)))
                    .addGroup(q7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(q7Layout.createSequentialGroup()
                                .addComponent(bck7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 751, Short.MAX_VALUE)
                                .addComponent(nxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        q7Layout.setVerticalGroup(
            q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(q7_a1)
                .addGap(54, 54, 54)
                .addComponent(q7_a2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bck7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q7Layout.createSequentialGroup()
                        .addComponent(nxt7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(27, 27, 27)))
                .addContainerGap(3, Short.MAX_VALUE))
        );

        Question_panel.add(q7, "card3");

        q8.setBackground(new java.awt.Color(153, 255, 255));
        q8.setMaximumSize(new java.awt.Dimension(1038, 670));
        q8.setPreferredSize(new java.awt.Dimension(1038, 670));

        jLabel9.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("What type of serving you prefer? ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        q8_a1.setBackground(new java.awt.Color(153, 255, 255));
        q8_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q8_a1.setText("Waffle");

        q8_a2.setBackground(new java.awt.Color(153, 255, 255));
        q8_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q8_a2.setText("Cup");

        bck8.setBackground(new java.awt.Color(0, 51, 51));
        bck8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck8.setForeground(new java.awt.Color(255, 255, 255));
        bck8.setText("Back");
        bck8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck8ActionPerformed(evt);
            }
        });

        nxt8.setBackground(new java.awt.Color(0, 51, 51));
        nxt8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt8.setForeground(new java.awt.Color(255, 255, 255));
        nxt8.setText("Next");
        nxt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q8Layout = new javax.swing.GroupLayout(q8);
        q8.setLayout(q8Layout);
        q8Layout.setHorizontalGroup(
            q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q8Layout.createSequentialGroup()
                .addGroup(q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q8Layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addGroup(q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q8_a2)
                            .addComponent(q8_a1)))
                    .addGroup(q8Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(q8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bck8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        q8Layout.setVerticalGroup(
            q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(q8_a1)
                .addGap(37, 37, 37)
                .addComponent(q8_a2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bck8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nxt8, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );

        Question_panel.add(q8, "card3");

        q9.setBackground(new java.awt.Color(153, 255, 255));

        jLabel10.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("What type of delivery mode you prefer?");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        q9_a1.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup9.add(q9_a1);
        q9_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q9_a1.setText("Dine inn");

        q9_a2.setBackground(new java.awt.Color(153, 255, 255));
        buttonGroup9.add(q9_a2);
        q9_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q9_a2.setText("Take Away");

        bck9.setBackground(new java.awt.Color(0, 51, 51));
        bck9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck9.setForeground(new java.awt.Color(255, 255, 255));
        bck9.setText("Back");
        bck9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck9ActionPerformed(evt);
            }
        });

        nxt9.setBackground(new java.awt.Color(0, 51, 51));
        nxt9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt9.setForeground(new java.awt.Color(255, 255, 255));
        nxt9.setText("Next");
        nxt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q9Layout = new javax.swing.GroupLayout(q9);
        q9.setLayout(q9Layout);
        q9Layout.setHorizontalGroup(
            q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q9_a2)
                    .addComponent(q9_a1))
                .addGap(440, 440, 440))
            .addGroup(q9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(q9Layout.createSequentialGroup()
                        .addComponent(bck9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        q9Layout.setVerticalGroup(
            q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(q9_a1)
                .addGap(48, 48, 48)
                .addComponent(q9_a2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bck9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Question_panel.add(q9, "card3");

        q10.setBackground(new java.awt.Color(153, 255, 255));

        jLabel11.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("What is your payment method? ");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        q10_a1.setBackground(new java.awt.Color(153, 255, 255));
        q10_a1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q10_a1.setText("Cash");

        q10_a2.setBackground(new java.awt.Color(153, 255, 255));
        q10_a2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q10_a2.setText("Card");

        q10_a3.setBackground(new java.awt.Color(153, 255, 255));
        q10_a3.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        q10_a3.setText("E-Wallet");

        bck10.setBackground(new java.awt.Color(0, 51, 51));
        bck10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bck10.setForeground(new java.awt.Color(255, 255, 255));
        bck10.setText("Back");
        bck10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck10ActionPerformed(evt);
            }
        });

        nxt10.setBackground(new java.awt.Color(0, 51, 51));
        nxt10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nxt10.setForeground(new java.awt.Color(255, 255, 255));
        nxt10.setText("Done");
        nxt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout q10Layout = new javax.swing.GroupLayout(q10);
        q10.setLayout(q10Layout);
        q10Layout.setHorizontalGroup(
            q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q10Layout.createSequentialGroup()
                .addGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(q10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bck10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nxt10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(q10Layout.createSequentialGroup()
                        .addGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(q10Layout.createSequentialGroup()
                                .addGap(438, 438, 438)
                                .addGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q10_a2)
                                    .addComponent(q10_a1)
                                    .addComponent(q10_a3)))
                            .addGroup(q10Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        q10Layout.setVerticalGroup(
            q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(q10Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(q10_a1)
                .addGap(38, 38, 38)
                .addComponent(q10_a2)
                .addGap(35, 35, 35)
                .addComponent(q10_a3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nxt10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bck10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Question_panel.add(q10, "card3");

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("\"You Decide, We Provide\"");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Question_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(80, 80, 80)
                .addComponent(Question_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt1ActionPerformed
        // TODO add your handling code here:
       q2.setVisible(true);
        q1.setVisible(false);
    }//GEN-LAST:event_nxt1ActionPerformed

    private void nxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nxt1MouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==nxt1){
        q2.setVisible(true);
        }
    }//GEN-LAST:event_nxt1MouseClicked

    private void bck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck2ActionPerformed
        // TODO add your handling code here:
        q2.setVisible(false);
        q1.setVisible(true);
    }//GEN-LAST:event_bck2ActionPerformed

    private void nxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt2ActionPerformed
        // TODO add your handling code here:
        q3.setVisible(true);
        q2.setVisible(false);
    }//GEN-LAST:event_nxt2ActionPerformed

    private void bck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck3ActionPerformed
        // TODO add your handling code here:
        q3.setVisible(false);
        q2.setVisible(true);
    }//GEN-LAST:event_bck3ActionPerformed

    private void nxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt3ActionPerformed
        // TODO add your handling code here:
        q4.setVisible(true);
        q3.setVisible(false);
    }//GEN-LAST:event_nxt3ActionPerformed

    private void bck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck4ActionPerformed
        // TODO add your handling code here:
        q4.setVisible(false);
        q3.setVisible(true);
        
    }//GEN-LAST:event_bck4ActionPerformed

    private void nxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt4ActionPerformed
        // TODO add your handling code here:
        q5.setVisible(true);
        q4.setVisible(false);
    }//GEN-LAST:event_nxt4ActionPerformed

    private void nxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt5ActionPerformed
        // TODO add your handling code here:
        q6.setVisible(true);
        q5.setVisible(false);
    }//GEN-LAST:event_nxt5ActionPerformed

    private void bck5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck5ActionPerformed
        // TODO add your handling code here:
        q5.setVisible(false);
        q4.setVisible(true);
    }//GEN-LAST:event_bck5ActionPerformed

    private void nxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt6ActionPerformed
        // TODO add your handling code here:
        q7.setVisible(true);
        q6.setVisible(false);
    }//GEN-LAST:event_nxt6ActionPerformed

    private void bck6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck6ActionPerformed
        // TODO add your handling code here:
        q6.setVisible(false);
        q5.setVisible(true);
    }//GEN-LAST:event_bck6ActionPerformed

    private void nxt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt7ActionPerformed
        // TODO add your handling code here:
        q8.setVisible(true);
        q7.setVisible(false);
    }//GEN-LAST:event_nxt7ActionPerformed

    private void bck7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck7ActionPerformed
        // TODO add your handling code here:
        q7.setVisible(false);
        q6.setVisible(true);
    }//GEN-LAST:event_bck7ActionPerformed

    private void bck8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck8ActionPerformed
        // TODO add your handling code here:
        q8.setVisible(false);
        q7.setVisible(true);
    }//GEN-LAST:event_bck8ActionPerformed

    private void nxt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt8ActionPerformed
        // TODO add your handling code here:
        q9.setVisible(true);
        q8.setVisible(false);
    }//GEN-LAST:event_nxt8ActionPerformed

    private void nxt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt9ActionPerformed
        // TODO add your handling code here:
        q9.setVisible(false);
        q10.setVisible(true);
    }//GEN-LAST:event_nxt9ActionPerformed

    private void bck9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck9ActionPerformed
        // TODO add your handling code here:
        q9.setVisible(false);
        q8.setVisible(true);
    }//GEN-LAST:event_bck9ActionPerformed

    private void bck10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck10ActionPerformed
        // TODO add your handling code here:
        q10.setVisible(false);
        q9.setVisible(true);
    }//GEN-LAST:event_bck10ActionPerformed

    private void nxt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt10ActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       q10.setVisible(false); q5.setVisible(false);
       q9.setVisible(false); q4.setVisible(false);
       q8.setVisible(false); q3.setVisible(false);
       q7.setVisible(false); q2.setVisible(false);
       q6.setVisible(false); q1.setVisible(false);
       Surprise surprise = new Surprise();
       surprise.setVisible(true);
        //bck10.setEnabled(false);
        
    }//GEN-LAST:event_nxt10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Question_panel;
    private javax.swing.JButton bck10;
    private javax.swing.JButton bck2;
    private javax.swing.JButton bck3;
    private javax.swing.JButton bck4;
    private javax.swing.JButton bck5;
    private javax.swing.JButton bck6;
    private javax.swing.JButton bck7;
    private javax.swing.JButton bck8;
    private javax.swing.JButton bck9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JButton nxt1;
    private javax.swing.JButton nxt10;
    private javax.swing.JButton nxt2;
    private javax.swing.JButton nxt3;
    private javax.swing.JButton nxt4;
    private javax.swing.JButton nxt5;
    private javax.swing.JButton nxt6;
    private javax.swing.JButton nxt7;
    private javax.swing.JButton nxt8;
    private javax.swing.JButton nxt9;
    private javax.swing.JPanel q1;
    private javax.swing.JPanel q10;
    private javax.swing.JRadioButton q10_a1;
    private javax.swing.JRadioButton q10_a2;
    private javax.swing.JRadioButton q10_a3;
    private javax.swing.JRadioButton q1_a1;
    private javax.swing.JRadioButton q1_a2;
    private javax.swing.JRadioButton q1_a3;
    private javax.swing.JPanel q2;
    private javax.swing.JRadioButton q2_a1;
    private javax.swing.JRadioButton q2_a2;
    private javax.swing.JPanel q3;
    private javax.swing.JRadioButton q3_a1;
    private javax.swing.JRadioButton q3_a2;
    private javax.swing.JRadioButton q3_a3;
    private javax.swing.JRadioButton q3_a4;
    private javax.swing.JPanel q4;
    private javax.swing.JRadioButton q4_a1;
    private javax.swing.JRadioButton q4_a2;
    private javax.swing.JRadioButton q4_a3;
    private javax.swing.JRadioButton q4_a4;
    private javax.swing.JPanel q5;
    private javax.swing.JRadioButton q5_a1;
    private javax.swing.JRadioButton q5_a2;
    private javax.swing.JRadioButton q5_a3;
    private javax.swing.JPanel q6;
    private javax.swing.JRadioButton q6_a1;
    private javax.swing.JRadioButton q6_a2;
    private javax.swing.JPanel q7;
    private javax.swing.JRadioButton q7_a1;
    private javax.swing.JRadioButton q7_a2;
    private javax.swing.JPanel q8;
    private javax.swing.JRadioButton q8_a1;
    private javax.swing.JRadioButton q8_a2;
    private javax.swing.JPanel q9;
    private javax.swing.JRadioButton q9_a1;
    private javax.swing.JRadioButton q9_a2;
    // End of variables declaration//GEN-END:variables
}
